version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: qafiyah-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web/out:/usr/share/nginx/html:ro
    networks:
      - qafiyah-net

networks:
  qafiyah-net:
    driver: bridge
